<script setup lang="ts">
import { Icon } from "@iconify/vue";
import { storeToRefs } from "pinia";

import { useCategoriesStore } from "@/stores/categories";

import EcwidLogo from "../icons/EcwidLogo.vue";
import AppContainer from "./AppContainer.vue";

const socials = [
  {
    icon: "mdi:facebook",
    href: "https://www.facebook.com/ecwid",
    label: "Follow us on Facebook",
  },
  {
    icon: "mdi:instagram",
    href: "https://www.instagram.com/ecwid",
    label: "Follow us on Instagram",
  },
  {
    icon: "mdi:twitter",
    href: "https://www.twitter.com/ecwid",
    label: "Follow us on Twitter",
  },
];

const { hierarchicalCategories } = storeToRefs(useCategoriesStore());
</script>

<template>
  <footer class="bg-slate-50 text-slate-500">
    <AppContainer>
      <div class="flex items-start justify-between py-12">
        <!-- Logo -->
        <RouterLink to="/" class="flex h-6 transition-colors hover:text-slate-950">
          <EcwidLogo class="h-full" />
        </RouterLink>

        <!-- Categories -->
        <div class="flex items-start gap-10">
          <div v-for="category in hierarchicalCategories" :key="category.id">
            <h3 class="text-sm tracking-wide font-semibold uppercase">
              <RouterLink
                :to="`/c/${category.customSlug || category.autogeneratedSlug}`"
                class="transition-colors hover:text-slate-950"
              >
                {{ category.name }}
              </RouterLink>
            </h3>
            <ul class="mt-2.5 space-y-1">
              <li v-for="subCategory in category.subCategories" :key="subCategory.id">
                <RouterLink
                  :to="`/c/${subCategory.customSlug || subCategory.autogeneratedSlug}`"
                  class="text-sm hover:text-slate-950 transition-colors"
                >
                  {{ subCategory.name }}
                </RouterLink>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <!-- Bottom -->
      <div class="flex items-center justify-between gap-4 border-t border-slate-200 py-10">
        <!-- Copyright -->
        <p class="text-sm">&copy; {{ new Date().getFullYear() }} Ecwid. All rights reserved.</p>

        <!-- Socials -->
        <div class="flex items-center gap-4">
          <a
            v-for="social in socials"
            :key="social.icon"
            :href="social.href"
            target="_blank"
            class="flex h-5 w-5 hover:text-slate-950 transition-colors"
            :aria-label="social.label"
          >
            <Icon :icon="social.icon" class="h-5 w-5" />
          </a>
        </div>
      </div>
    </AppContainer>
  </footer>
</template>
