<script setup lang="ts">
import { Icon } from "@iconify/vue";
import { computed, provide } from "vue";
import { RouterLink } from "vue-router";

import { type EcwidCategory } from "@/api/categories.types";
import CommonSkeletonText from "@/components/common/CommonSkeletonText.vue";

interface Props {
  category?: EcwidCategory & { subCategories?: EcwidCategory[] };
}

const { category } = defineProps<Props>();

const isLoading = computed(() => !category);

provide("loading", isLoading);

const categorySlug = computed(() => category?.customSlug || category?.autogeneratedSlug);

const hasSubcategories = computed(() =>
  isLoading.value ? true : category?.subCategories && category.subCategories.length > 0,
);
</script>

<template>
  <div class="bg-slate-950 text-slate-400 rounded-2xl overflow-hidden p-5">
    <!-- Category Name -->
    <h3
      class="text-lg uppercase font-semibold tracking-wide text-slate-50 hover:text-yellow-400 transition-colors"
    >
      <CommonSkeletonText background-class="bg-white/20" :lines="1">
        <RouterLink v-if="category && categorySlug" :to="`/c/${categorySlug}`">
          {{ category?.name }}
        </RouterLink>
      </CommonSkeletonText>
    </h3>

    <!-- Product Count -->
    <p class="text-sm mt-1">
      <CommonSkeletonText
        background-class="bg-white/20"
        :random="false"
        :lines="1"
        class="w-20"
        rounded-class="rounded-md"
      >
        {{ category?.productCount || 0 }} product{{ category?.productCount === 1 ? "" : "s" }}
      </CommonSkeletonText>
    </p>

    <!-- Subcategories -->
    <div v-if="hasSubcategories" class="mt-4">
      <ul class="space-y-1">
        <li
          v-for="(subCategory, subCategoryIndex) in isLoading
            ? Array(2).fill(null)
            : category?.subCategories"
          :key="subCategory?.id ?? subCategoryIndex"
          class="flex items-center gap-1.5"
        >
          <!-- Icon -->
          <Icon icon="mdi:chevron-right" class="w-4 h-4 shrink-0 text-yellow-300" />

          <!-- Name -->
          <div class="flex-1 text-sm">
            <CommonSkeletonText
              background-class="bg-white/20"
              :lines="1"
              rounded-class="rounded-md"
            >
              <RouterLink
                :to="`/c/${subCategory.customSlug || subCategory.autogeneratedSlug}`"
                class="hover:text-slate-50 transition-colors"
              >
                {{ subCategory.name }}
              </RouterLink>
            </CommonSkeletonText>
          </div>
        </li>
      </ul>
    </div>
  </div>
</template>
