<script setup lang="ts">
import { computed, provide } from "vue";

import { type EcwidProduct } from "@/api/product.types";
import CommonBreadcrumbs from "@/components/common/CommonBreadcrumbs.vue";
import { useCategoriesStore } from "@/stores/categories";
import { generateProductUrl } from "@/utils/product";

interface Props {
  product?: EcwidProduct;
}

const { product } = defineProps<Props>();

const isLoading = computed(() => !product);

provide("loading", isLoading);

const categoriesStore = useCategoriesStore();
const { getCategoryParents } = categoriesStore;

const breadcrumbs = computed(() => {
  if (!product?.defaultCategoryId) return [];

  const category = categoriesStore.categories.find((c) => c.id === product.defaultCategoryId);
  if (!category) return [];

  const parents = getCategoryParents(category.id);

  return [
    ...parents.map((parent) => ({
      label: parent.name,
      href: `/c/${parent.customSlug || parent.autogeneratedSlug}`,
    })),
    {
      label: category.name,
      href: `/c/${category.customSlug || category.autogeneratedSlug}`,
    },
    {
      label: product.name,
      href: generateProductUrl(product),
    },
  ];
});
</script>

<template>
  <CommonBreadcrumbs :loading="isLoading" :items="breadcrumbs" />
</template>
