<script setup lang="ts">
import { useQuery } from "@tanstack/vue-query";
import { storeToRefs } from "pinia";
import { computed } from "vue";
import { useRoute } from "vue-router";

import { ecwidApi } from "@/api";
import AppContainer from "@/components/app/AppContainer.vue";
import CommonBreadcrumbs from "@/components/common/CommonBreadcrumbs.vue";
import ProductCard from "@/components/product/ProductCard.vue";
import { useCategoriesStore } from "@/stores/categories";

const route = useRoute();

const categoriesStore = useCategoriesStore();
const { getCategoryBySlug, getCategoryParents } = categoriesStore;
const { categoriesLoading } = storeToRefs(categoriesStore);

const category = computed(() => getCategoryBySlug(route.params.slug as string));

const breadcrumbs = computed(() => {
  if (!category.value) return [];

  const parents = getCategoryParents(category.value?.id ?? 0);

  return [
    ...parents.map((parent) => ({
      label: parent.name,
      href: `/c/${parent.customSlug || parent.autogeneratedSlug}`,
    })),
    {
      label: category.value.name,
      href: `/c/${category.value.customSlug || category.value.autogeneratedSlug}`,
    },
  ];
});

const queryKey = computed(() => ["products", category.value?.id]);

const { data: products } = useQuery({
  queryKey,
  queryFn: () => ecwidApi.product.list({ category: String(category.value?.id ?? 0) }),
});
</script>

<template>
  <main class="pt-7 pb-12">
    <AppContainer>
      <CommonBreadcrumbs :loading="categoriesLoading" :items="breadcrumbs" class="mb-4" />
      <h1 class="text-5xl font-medium uppercase tracking-wider text-slate-950">
        {{ category?.name }}
      </h1>
      <div class="mt-9">
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
          <ProductCard
            v-for="(product, productIndex) in products?.data.items ?? Array(8)"
            :key="productIndex"
            :product="product"
          />
        </div>
      </div>
    </AppContainer>
  </main>
</template>
