<script setup lang="ts">
import { Icon } from "@iconify/vue";
import { useQuery } from "@tanstack/vue-query";
import { storeToRefs } from "pinia";
import { computed, provide, ref, watch } from "vue";
import { RouterLink, useRoute } from "vue-router";

import { ecwidApi } from "@/api";
import AppContainer from "@/components/app/AppContainer.vue";
import CommonBreadcrumbs from "@/components/common/CommonBreadcrumbs.vue";
import CommonPagination from "@/components/common/CommonPagination.vue";
import CommonSkeletonText from "@/components/common/CommonSkeletonText.vue";
import ProductCard from "@/components/product/ProductCard.vue";
import { useCategoriesStore } from "@/stores/categories";

const route = useRoute();

const categoriesStore = useCategoriesStore();
const { getCategoryBySlug, getCategoryParents } = categoriesStore;
const { categoriesLoading } = storeToRefs(categoriesStore);

const category = computed(() => getCategoryBySlug(route.params.slug as string));

// Product total ref
const productTotal = ref<number>(0);

// Watch for category changes and reset total
watch(category, () => {
  productTotal.value = 0;
});

// Pagination logic
const currentPage = computed(() => {
  const page = Number(route.query.page) || 1;
  return Math.max(1, page);
});

const limit = 12;
const offset = computed(() => (currentPage.value - 1) * limit);

const breadcrumbs = computed(() => {
  if (!category.value) return [];

  const parents = getCategoryParents(category.value?.id ?? 0);

  return [
    ...parents.map((parent) => ({
      label: parent.name,
      href: `/c/${parent.customSlug || parent.autogeneratedSlug}`,
    })),
    {
      label: category.value.name,
      href: `/c/${category.value.customSlug || category.value.autogeneratedSlug}`,
    },
  ];
});

const queryKey = computed(() => ["products", category.value?.id, currentPage.value, limit]);

const { data: products, isLoading: productsLoading } = useQuery({
  queryKey,
  queryFn: () =>
    ecwidApi.product.list({
      category: String(category.value?.id ?? 0),
      limit,
      offset: offset.value,
    }),
});

// Update product total when products data changes
watch(products, (newProducts) => {
  if (newProducts?.data.total !== undefined) {
    productTotal.value = newProducts.data.total;
  }
});

// Pagination data
const totalPages = computed(() => {
  if (!productTotal.value) return 1;
  return Math.ceil(productTotal.value / limit);
});

const baseUrl = computed(
  () => `/c/${category.value?.customSlug || category.value?.autogeneratedSlug}`,
);

// Get subcategories for current category
const subcategories = computed(() => {
  if (!category.value) return Array(2).fill(null);
  return categoriesStore.categories.filter((cat) => cat.parentId === category.value?.id);
});

provide("loading", productsLoading);
</script>

<template>
  <main class="pt-7 pb-24">
    <AppContainer>
      <CommonBreadcrumbs :loading="categoriesLoading" :items="breadcrumbs" class="mb-4" />
      <h1 class="text-5xl font-semibold uppercase tracking-wide text-slate-950">
        <CommonSkeletonText :lines="1" rounded-class="rounded-lg">
          {{ category?.name }}
        </CommonSkeletonText>
      </h1>

      <!-- Subcategories -->
      <div v-if="subcategories.length > 0" class="mt-3">
        <ul class="flex flex-wrap gap-6">
          <li
            v-for="subcategory in subcategories"
            :key="subcategory.id"
            class="flex items-start gap-1.5 text-slate-600"
          >
            <Icon icon="mdi:arrow-right-bottom" class="w-4 h-4 shrink-0 mt-0.5" />
            <CommonSkeletonText :lines="1" :random="false" class="w-30">
              <RouterLink
                :to="`/c/${subcategory.customSlug || subcategory.autogeneratedSlug}`"
                class="hover:text-slate-950 transition-colors"
              >
                {{ subcategory?.name }}
              </RouterLink>
            </CommonSkeletonText>
          </li>
        </ul>
      </div>

      <div class="mt-9">
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
          <ProductCard
            v-for="(product, productIndex) in products?.data.items ?? Array(limit)"
            :key="productIndex"
            :product="product"
          />
        </div>
      </div>

      <CommonPagination
        class="mt-7"
        :current-page="currentPage"
        :total-pages="totalPages"
        :base-url="baseUrl"
        :loading="productsLoading"
        :total-items="productTotal"
      />
    </AppContainer>
  </main>
</template>
