<script setup lang="ts">
import { useQuery } from "@tanstack/vue-query";
import { storeToRefs } from "pinia";
import { computed } from "vue";
import { useRoute } from "vue-router";

import { ecwidApi } from "@/api";
import AppContainer from "@/components/app/AppContainer.vue";
import CommonBreadcrumbs from "@/components/common/CommonBreadcrumbs.vue";
import CommonPagination from "@/components/common/CommonPagination.vue";
import ProductCard from "@/components/product/ProductCard.vue";
import { useCategoriesStore } from "@/stores/categories";

const route = useRoute();

const categoriesStore = useCategoriesStore();
const { getCategoryBySlug, getCategoryParents } = categoriesStore;
const { categoriesLoading } = storeToRefs(categoriesStore);

const category = computed(() => getCategoryBySlug(route.params.slug as string));

// Pagination logic
const currentPage = computed(() => {
  const page = Number(route.query.page) || 1;
  return Math.max(1, page);
});

const limit = 2;
const offset = computed(() => (currentPage.value - 1) * limit);

const breadcrumbs = computed(() => {
  if (!category.value) return [];

  const parents = getCategoryParents(category.value?.id ?? 0);

  return [
    ...parents.map((parent) => ({
      label: parent.name,
      href: `/c/${parent.customSlug || parent.autogeneratedSlug}`,
    })),
    {
      label: category.value.name,
      href: `/c/${category.value.customSlug || category.value.autogeneratedSlug}`,
    },
  ];
});

const queryKey = computed(() => ["products", category.value?.id, currentPage.value, limit]);

const { data: products, isLoading: productsLoading } = useQuery({
  queryKey,
  queryFn: () =>
    ecwidApi.product.list({
      category: String(category.value?.id ?? 0),
      limit,
      offset: offset.value,
    }),
});

// Pagination data
const totalPages = computed(() => {
  if (!products.value?.data.total) return 1;
  return Math.ceil(products.value.data.total / limit);
});

const baseUrl = computed(
  () => `/c/${category.value?.customSlug || category.value?.autogeneratedSlug}`,
);
</script>

<template>
  <main class="pt-7 pb-12">
    <AppContainer>
      <CommonBreadcrumbs :loading="categoriesLoading" :items="breadcrumbs" class="mb-4" />
      <h1 class="text-5xl font-medium uppercase tracking-wider text-slate-950">
        {{ category?.name }}
      </h1>
      <div class="mt-9">
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
          <ProductCard
            v-for="(product, productIndex) in products?.data.items ?? Array(limit)"
            :key="productIndex"
            :product="product"
          />
        </div>
      </div>

      <CommonPagination
        class="mt-7"
        :current-page="currentPage"
        :total-pages="totalPages"
        :base-url="baseUrl"
        :loading="productsLoading"
        :total-items="products?.data.total"
      />
    </AppContainer>
  </main>
</template>
