export enum EcwidCategoryOrigin {
  LIGHTSPEED = "LIGHTSPEED",
  ECWID = "ECWID",
  X_SERIES = "X-SERIES",
}

export interface EcwidCategory {
  id: number;
  parentId: number;
  orderBy: number;
  hdThumbnailUrl: string;
  thumbnailUrl: string;
  imageUrl: string;
  originalImageUrl: string;
  imageExternalId: string;
  name: string;
  nameTranslated: Record<string, string>;
  originalImage: {
    url: string;
    width: number;
    height: number;
  };
  thumbnail: {
    url: string;
    width: number;
    height: number;
  };
  origin: EcwidCategoryOrigin;
  url: string;
  autogeneratedSlug: string;
  customSlug: string;
  productCount: number;
  enabledProductCount: number;
  description: string;
  descriptionTranslated: Record<string, string>;
  enabled: boolean;
  productIds: number[];
  seoTitle: string;
  seoTitleTranslated: string;
  seoDescription: string;
  seoDescriptionTranslated: string;
  alt: {
    main: string;
    translations: Record<string, string>;
  };
  externalReferenceId?: string;
}

export type EcwidCategoryListRequestParams = {
  keyword?: string;
  parent?: number;
  parentIds?: string;
  withSubcategories?: boolean;
  hidden_categories?: boolean;
  offset?: number;
  limit?: number;
  lang?: string;
  responseFields?: string;
};

export type EcwidCategoryRequestParams = {
  baseUrl?: string;
  cleanURLs?: boolean;
  slugsWithoutIds?: boolean;
  lang?: string;
  responseFields?: string;
};
